"""
Structured trade decision log.

Appends one JSON line per evaluation cycle to a daily log file:
    logs/trade_log_YYYYMMDD.jsonl

Each entry captures the complete pipeline context for audit and analysis:
  - signal generated by the strategy
  - gate outcomes (entry window, affordability)
  - risk engine decision
  - order ID if submitted
  - final outcome label

This is the primary audit trail for all bot activity.
Outcome values:
    "hold"                   — strategy said HOLD, nothing done
    "rejected_confidence"    — signal fired but confidence < 0.5
    "rejected_affordability" — affordability gate failed
    "rejected_risk"          — risk engine pre_trade_check rejected
    "dry_run"                — all gates passed, but DRY_RUN=true
    "submitted"              — order placed with broker
    "error"                  — unexpected exception during pipeline
"""

import json
import logging
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# TradeDecision dataclass
# ---------------------------------------------------------------------------


@dataclass
class TradeDecision:
    """Full record of a single trade evaluation cycle."""

    # Context
    timestamp: str  # ISO 8601 UTC string
    symbol: str
    strategy: str  # "A" | "B" | "C"
    cycle_count: int  # monotonic counter for this session

    # Signal
    signal_direction: str  # "buy" | "sell" | "hold"
    signal_confidence: float
    signal_rationale: str
    signal_metadata: Dict[str, Any] = field(default_factory=dict)

    # Gates
    entry_window_passed: bool = True
    affordability_passed: Optional[bool] = None
    affordability_reason: Optional[str] = None
    reduce_size: bool = False

    # Risk engine
    risk_approved: Optional[bool] = None
    risk_rejections: List[str] = field(default_factory=list)

    # Execution
    outcome: str = "hold"  # see module docstring
    order_id: Optional[int] = None
    premium_used: Optional[float] = None
    quantity: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to plain dictionary for JSON output."""
        return asdict(self)


# ---------------------------------------------------------------------------
# TradeLog writer
# ---------------------------------------------------------------------------


class TradeLog:
    """
    Appends TradeDecision records to a daily JSONL file.

    File path: ``<log_dir>/trade_log_YYYYMMDD.jsonl``

    Each line in the file is a complete JSON object so the file is
    trivially tail-able and parseable with standard tools.

    Usage::

        trade_log = TradeLog(Path("logs"))
        trade_log.record(decision)
    """

    def __init__(self, log_dir: Path) -> None:
        """
        Initialize the trade log.

        Args:
            log_dir: Directory for log files. Created on first write if absent.
        """
        self._log_dir = log_dir
        self._buffer: List[TradeDecision] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def record(self, decision: TradeDecision) -> None:
        """
        Append a trade decision to today's log file and in-memory buffer.

        Args:
            decision: Fully populated TradeDecision to record.
        """
        self._buffer.append(decision)
        path = self._log_path()
        self._ensure_dir()
        try:
            with open(path, "a", encoding="utf-8") as fh:
                fh.write(json.dumps(decision.to_dict()) + "\n")
        except OSError as exc:
            logger.error("TradeLog: failed to write to %s: %s", path, exc)

    def get_buffer(self) -> List[TradeDecision]:
        """Return all decisions recorded during this session (in-memory only)."""
        return list(self._buffer)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _log_path(self, today: Optional[date] = None) -> Path:
        d = today or datetime.now(timezone.utc).date()
        return self._log_dir / f"trade_log_{d.strftime('%Y%m%d')}.jsonl"

    def _ensure_dir(self) -> None:
        try:
            self._log_dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            logger.error("TradeLog: cannot create log directory %s: %s", self._log_dir, exc)
